id = "killstata"
name = "Killstata"
description = "The open source coding agent."
version = "1.1.31"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/killstata"

[agent_servers.killstata]
name = "Killstata"
icon = "./icons/killstata.svg"

[agent_servers.killstata.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/killstata/releases/download/v1.1.31/killstata-darwin-arm64.zip"
cmd = "./killstata"
args = ["acp"]

[agent_servers.killstata.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/killstata/releases/download/v1.1.31/killstata-darwin-x64.zip"
cmd = "./killstata"
args = ["acp"]

[agent_servers.killstata.targets.linux-aarch64]
archive = "https://github.com/anomalyco/killstata/releases/download/v1.1.31/killstata-linux-arm64.tar.gz"
cmd = "./killstata"
args = ["acp"]

[agent_servers.killstata.targets.linux-x86_64]
archive = "https://github.com/anomalyco/killstata/releases/download/v1.1.31/killstata-linux-x64.tar.gz"
cmd = "./killstata"
args = ["acp"]

[agent_servers.killstata.targets.windows-x86_64]
archive = "https://github.com/anomalyco/killstata/releases/download/v1.1.31/killstata-windows-x64.zip"
cmd = "./killstata.exe"
args = ["acp"]
