name: test

on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Typecheck
        run: bun turbo typecheck

      - name: Test
        run: bun turbo test
